# Generated by Django 5.0 on 2025-12-08 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_created_at_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='videos', to='videos.category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category (deprecated - use categories)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_videos', to='videos.category'),
        ),
        migrations.CreateModel(
            name='VideoTierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.FloatField(default=0.0, help_text='Reward amount for this tier')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.tier')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_prices', to='videos.video')),
            ],
            options={
                'unique_together': {('video', 'tier')},
            },
        ),
    ]
