# Generated by Django 5.0 on 2026-01-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_categories_alter_video_category_videotierprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='countries',
            field=models.CharField(blank=True, default='', help_text='Comma-separated ISO country codes where this video is available. Blank = global', max_length=200),
        ),
    ]
