# Generated by Django 5.0 on 2026-09-02 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_file_watchheartbeat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reward credited on completion. Falls back to `reward` if 0.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration_seconds',
            field=models.IntegerField(default=30, help_text='Watch duration in seconds required to earn the reward.'),
        ),
        migrations.CreateModel(
            name='WatchCompletionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('elapsed_seconds', models.IntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
                ('reason', models.CharField(default='', help_text='e.g. credited, duplicate, too_soon, no_session', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_attempts', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_attempts', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Per-tab UUID from the client.', max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('credited', models.BooleanField(default=False)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('amount_credited', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watches', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='videos.video')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'credited'], name='videos_vide_user_id_97c4f9_idx'), models.Index(fields=['video', 'credited'], name='videos_vide_video_i_0d4184_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='videowatch',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='videos_videowatch_unique_user_video'),
        ),
        migrations.AddIndex(
            model_name='watchcompletionattempt',
            index=models.Index(fields=['user', '-created_at'], name='videos_watc_user_id_a016cd_idx'),
        ),
        migrations.AddIndex(
            model_name='watchcompletionattempt',
            index=models.Index(fields=['video', 'accepted'], name='videos_watc_video_i_9a7ffc_idx'),
        ),
    ]
