# Generated by Django 5.0 on 2026-09-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_reward_amount_alter_video_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='daily_watch_limit',
            field=models.IntegerField(default=1, help_text='Maximum videos a user can watch per day. 0 = unlimited.'),
        ),
    ]
