# Generated by Django 5.0 on 2025-12-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='admin@xrpvideos.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_video_reward',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Default reward for watching videos', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_referrals_for_withdrawal',
            field=models.IntegerField(default=7, help_text='Minimum referrals required to withdraw'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum amount users can withdraw', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referral_bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Referral commission percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='xrpvideos', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='withdrawal_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Withdrawal fee percentage (0-100)', max_digits=5),
        ),
    ]
