# Generated by Django 5.0 on 2026-01-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('countries', models.CharField(blank=True, help_text='Comma-separated ISO country codes (e.g. US,GB,KE). Blank = all countries', max_length=200)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('instructions', models.TextField(blank=True, help_text='Payment instructions or account details')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
