# Generated by Django 5.0 on 2026-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_seed_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoption',
            name='crypto_network',
            field=models.CharField(blank=True, choices=[('SOL', 'Solana (SOL)'), ('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)')], help_text='Cryptocurrency network', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='payment_type',
            field=models.CharField(choices=[('mpesa_till', 'M-Pesa Till'), ('crypto_wallet', 'Crypto Wallet')], default='mpesa_till', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='till_number',
            field=models.CharField(blank=True, help_text='M-Pesa Till Number (e.g. 156307)', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Crypto wallet address', max_length=255),
        ),
    ]
