# Generated by Django 5.2.9 on 2025-12-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_tier',
            field=models.ForeignKey(blank=True, help_text='Current tier the user has access to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.tier'),
        ),
    ]
