# Generated by Django 5.0 on 2026-09-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_accepted_terms_at_profile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='payment_type',
            field=models.CharField(choices=[('mpesa_till', 'M-Pesa Till'), ('crypto_wallet', 'Crypto Wallet')], default='mpesa_till', max_length=20),
        ),
    ]
