# Generated by Django 5.0 on 2026-09-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_payment_type_to_paymentattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='stripe_payment_intent',
        ),
    ]
